import React, { useRef, useState } from 'react';
import './ImageGenerator.css';
import default_image from '../Assets/default_image.svg';

const ImageGenerator = () => {
  const [image_url, setImage_url] = useState("/");
  const [isLoading, setIsLoading] = useState(false);  // Loading state
  let inputRef = useRef(null);

  const imageGenerator = async () => {
    setIsLoading(true);  // Set loading to true when the request starts

    if (inputRef.current.value === "") {
      setIsLoading(false);  // Set loading to false if the input is empty
      return 0;
    }

    const response = await fetch(
      'https://api.openai.com/v1/images/generations',
      {
        method: 'POST',
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.REACT_APP_OPENAI_API_KEY}`,
        },
        body: JSON.stringify({
          "prompt": `${inputRef.current.value}`,
          n: 1,
          size: '512x512',
        }),
      }
    );
    
    if (!response.ok) {
      console.error(`Error: ${response.status}`);
      setIsLoading(false);  // Set loading to false if the request fails
      return;
    }

    let data = await response.json();

    if (data && data.data && data.data.length > 0) {
      setImage_url(data.data[0].url);
    } else {
      console.error('Unexpected API response', data);
    }

    setIsLoading(false);  // Set loading to false when the request completes
  }

  return (
    <div className='ai-image-generator'>
      <div className='header'>Ai image <span>generator</span></div>
      <div className="img-loading">
        <div className="image">
          <img src={image_url === "/" ? default_image : image_url} alt="Generated by AI" />
        </div>
        {isLoading && (  // Conditionally render the loading widget
          <div className="loading">
            <div className="loading-bar">
              {/* Loading... */}
            </div>
          </div>
        )}
      </div>
      <div className="search-box">
        <input type="text" ref={inputRef} className='search-input' placeholder='Describe What You Want To See' />
        <div className="generate-btn" onClick={() => { imageGenerator() }}>Generate</div>
      </div>
    </div>
  )
}

export default ImageGenerator;
